// CONFIGURACION REALIZADA PARA DESPLIEGUE CON VITE Y LO HACE CON OTRO CLOUD SIGNAR VARIABLE SEGUN DOCUMENTACION DEL CLOUD

export const URLBASE = import.meta.env.VITE_BACKEND || "http://127.0.0.1:8000/api/"

export const URLFRONT = import.meta.env.VITE_FRONT || "http://localhost:5173"